export const PHONE_VALIDATE_ACTION = 'PHONE_VALIDATE_ACTION';
export const PHONE_VALIDATE_START = 'PHONE_VALIDATE_START';
export const PHONE_VALIDATE_SUCCESS = 'PHONE_VALIDATE_SUCCESS';
export const PHONE_VALIDATE_FAILRULE = 'PHONE_VALIDATE_FAILRULE';

export const GETIP_ACTION = 'GETIP_ACTION';
export const GETIP_START = 'GETIP_START';
export const GETIP_SUCCESS = 'GETIP_SUCCESS';
export const GETIP_FAILRULE = 'GETIP_FAILRULE';